package pg.autyzm.friendlyemotions.domain.model.runtime

import pg.autyzm.friendlyemotions.domain.model.emotion.EmotionId
import pg.autyzm.friendlyemotions.domain.model.emotion.GrammaticalGender

/**
 * Generated by `TrialGenerator` for each session; never persisted (target-domain.md §4.13).
 * [promptGender] is always derived from [correctOption]'s gender and is fixed at generation time —
 * distractors' genders never affect it (§4.1, §8.8).
 */
data class Trial(
    val targetEmotionId: EmotionId,
    val promptGender: GrammaticalGender,
    val correctOption: TrialOption,
    val allOptions: List<TrialOption>,
)
